### PR TITLE
app: generally allow entering custom ABI

### PR DESCRIPTION
**Pull request by jfschwarz**
So far the app only allowed entering custom ABI if fetching it failed. We now generally give the option to paste ABI so there's an escape hatch in case the fetched ABI wrong, e.g. due to undetected proxy contracts.

This PR also includes a fix for #173.

It also slightly improves the proxy detection implemented in #179 

Should not be merged before #184.

### CODE REVIEW

**Review by manboy-eth — COMMENTED** [review]
Nice work.

Some comments:
It seems like there is no easy way of removing the custom ABI.

When adding a custom ABI and moving to a different target, the custom ABI is still in the input field.

Not sure exactly how this things should be handled 🤔

**Comment by jfschwarz** [comment]
> Some comments: It seems like there is no easy way of removing the custom ABI.
> 
> When adding a custom ABI and moving to a different target, the custom ABI is still in the input field.

Good points. I've improved the handling a bit. You can now clear the custom ABI and go back to the fetched one by clearing the textarea and submitting.

We now also just discard the custom ABI when switching between targets. This is not optimal, but should be good enough for now. Later on we should consider keeping custom entered ABIs persisted in localforage.

**Review by manboy-eth — COMMENTED** [review]
Much better now :)

However, I found another thing, when adding a custom ABI to a target that already has an ABI and then removing it again, some "unknown" functions are kept at the end. Also, it seems like the functions from the original ABI are still present after adding a custom ABI, even though they do not have any permissions.

**Example**
Original:
Screenshot 2023-02-10 at 10 42 18

Custom ABI:
Screenshot 2023-02-10 at 10 44 20


Custom ABI removed:
Screenshot 2023-02-10 at 10 44 54

**Comment by jfschwarz** [comment]
should be fixed now

**Review by manboy-eth — APPROVED** [review]
Nice :D LGTM!

**Pull request merged**
